### PR TITLE
Add info to package.json

### PR DESCRIPTION
**Pull request by noskov**

### CODE REVIEW

**Comment by Aetles** [comment]
This also contained changes in `css/foundation.css`, `css/foundation.css.map` and `js/foundation.js`, was that deliberate?

**Comment by noskov** [comment]
Hi @Aetles ,
Nope, it was just "grunt build". I have made no changes to styles/scripts.

**Comment by olefredrik** [comment]
@Aetles : ```css/foundation.css```, ```css/foundaiton.css.map``` and ```js/foundation.js``` will automatically be changed whenever you do a  ```grunt build```. Would it be a good idea to add these files in ```.gitignore```? Does it make any sense to track changes in these files? What do you think?

**Comment by noskov** [comment]
@olefredrik ,
I think so, it's a good idea. In any case I don't see any reason to track all these changes in the main repo.
+1 to ignore them.

**Comment by Aetles** [comment]
Ah, that's what I thought, all changes seemed unimportant, as if they came from a slightly different grunt build (like `#fff` to `#FFFFFF`). There where some path changes in the .map file, but those seemed to be correct. Just wanted to make sure, diffs of minified files are hard to read :) 

Anyway, about adding them to .gitignore: that makes sense, since they are part of the build process. It would make pull requests less likely to include extra files. I can't think of a good reason to track them right now. If someone need them in their clone of FoundationPress they can always delete the lines from .gitignore.

**Pull request merged**
