### PR TITLE
Added Child Theme Support

### PR DESCRIPTION
**Pull request by themestechnology**
Added !function_exists( for child theme support

Also added FoundationPress_ prefix to some functions to standardise
their name (will help to avoid conflicts with plugins etc).

### CODE REVIEW

**Comment by themestechnology** [comment]
Noww added Missing Core Jquery Scripts

**Comment by dotmagic** [comment]
Thank you, almost perfect. There's just a small typo :)
https://github.com/olefredrik/FoundationPress/blob/master/library/widget-areas.php

**Comment by themestechnology** [comment]
How that did not appear during testing is beyond me, but I have done a pull request to fix that anyhow

**Comment by dotmagic** [comment]
Thanks for ultra fast fixing!

**Pull request merged**
