### PR TITLE
Breadcrumb helper function

### PR DESCRIPTION
**Pull request by Larzans**
Adapted the breadcrumb solution by thewebtaylor (http://thewebtaylor.com/articles/wordpress-creating-breadcrumbs-without-a-plugin) for FoundationPress

### CODE REVIEW

**Comment by olefredrik** [comment]
Hi. Thanks for your pull request. Unfortunately the Travis CI build failed. Could you check the details, fix the issues and add push a new commit? https://travis-ci.org/olefredrik/FoundationPress/jobs/63924272

Thanks.

**Comment by Larzans** [comment]
Sure, i hope this fixes that :)

**Comment by olefredrik** [comment]
Hm. I'm unable to restart the travis build because the pull request can no longer be automatically merged. There seems to be merge conflicts that needs to be resolved first.

**Comment by Larzans** [comment]
Hm, ok, makes sense, i used PHPCBF to remove the travis errors, it also changed the rest of the content in the file to make it more standard conform.
Let me revert and just add the new 'clean' function, just a minute.

**Comment by Larzans** [comment]
Ok, it looks like my ide changed the file even before the PHCBF, sorry about all the trouble, i will just overwrite it with the master navigation.php and then add the new function with another ide.

**Comment by Larzans** [comment]
Eherm. i am using the wrong rules for phpcbs :|
Gonna fix that and commit again.

**Comment by Larzans** [comment]
I am sorry, but i have problems with my codesniffer setup, could you help me please?
I installed the wpcs repository and am using it together with the codesniffer.ruleset.xml from foundationpress, but it shows me different errors from the one in the Travis builds.

Is there anything else i have to take into account?

The command line looks like this: 
phpcs.bat -p -s -v -n --standard="FoundationPress\codesniffer.ruleset.xml" "FoundationPress\library\navigation.php"

**Comment by olefredrik** [comment]
Hello. To be honest I'm quite new with WordPress Coding Standards. Personally, I believe that many of the rules are too rigid. It's not like we're hacking the WP Core, after all. I've added the most useless rules on the exclusion list. I haven't tried setting up codesniffer for automatic correction of errors, actually. I fix all my errors manually. For me it makes no sense that codesniffer should show you different errors from the one in the Travis builds, if you copied my codesniffer ruleset. That's really strange. One option would be to fix the errors manually. It's insanely boring, I know. But I suppose it will be worth it when the build eventually passes.

**Comment by Larzans** [comment]
Haha, glad that you said that, i started to feel quite stupid with all the rules i supposedly broke :)
I will test a bit more tomorrow and if nothing werks i will bite the bullet and do it manually too, i just couldn't bring myself to do it as i thought it might be useful in the future to get the automatic wp-rule-purge up and running, but i do think as well that some rules are a bit too strict / exaggerated.
Cross my fingers that it does not come to that though, but i am almost out of ideas...

**Comment by Aetles** [comment]
Just a side note: As being one of those who enjoyed the effort of having FoundationPress following the WP code standard I'd say it's more about consistency than anything else (and the belief that consistent code is easier to read, easier to automatically review and could prevent errors). Could have been another code standard for all I care. I'm not particularly keen on the WP code standard from a personal point of view (took quite a while to get used to all those spaces) but since this is part of the WP world it does seem like a natural choice.

**Comment by Larzans** [comment]
Finally! Kinda satisfying i have to admit :)

**Comment by olefredrik** [comment]
Brilliant! Thanks a lot! :)

**Comment by Larzans** [comment]
Great, thanks for this wonderful project, saved me tons of time :)

**Comment by aibrean** [comment]
Doesn't work with custom post types though.

**Comment by Larzans** [comment]
Hmm, didn't test it with custom post types, i will check that out.

**Comment by AdamChlan** [comment]
I feel like I remember seeing an email coming across saying that CPTs were now supported with breadcrumbs, but I'm unable to find it in the issue tracker. Was this just my imagination?

**Pull request merged**
