### PR TITLE
Add toggle menu into Top Bar

### PR DESCRIPTION
**Pull request by AdamChlan**
In some projects I use the Top Bar mobile interface instead of the off canvas. It looks like this file does not have the the code for the toggle menu. Perhaps there was a reason it was not included, but if not, I've added it in.

### CODE REVIEW

**Comment by dantahoua** [comment]
Good idea... Maybe also it would be good to add an option or something like that in the theme to be able to switch off "off-canvas" when we do not need it. It could also remove the "off-canvas-wrap" (that create problem for 100% height stuff)...

**Comment by jw86** [comment]
I agree it would be great to have have an option to select either off-canvas or top-bar for smaller devices

**Comment by AdamChlan** [comment]
I have been wanting to explore the theme options functionality, so I will try to get to this as time allows.

**Comment by jw86** [comment]
Did you delete the off canvas code from the project you used the top-bar on?

**Comment by AdamChlan** [comment]
Yes, removed off canvas code, and updated visibility classes to make the top-bar show up on small. Then added in the line of code I proposed in this pull request.

**Comment by olefredrik** [comment]
I also agree that it would be useful to be able to switch between off-canvas and top-bar on mobile in wp-admin. I will not merge this pull request, as I can't see how it would add any direct value in terms of functionality. But I appreciate your contribution and would definitely like to be seeing a solution on switching between different types of mobile navigation patterns in wp-admin dashboard.

**Pull request closed without merging**
