### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by GarySwift**

### CODE REVIEW

**Comment by olefredrik** [comment]
Hi @GarySwift ,

I suspect this pull request to the FoundationPress master-branch was created by mistake? :)

**Comment by GarySwift** [comment]
Yes, sorry about that Ole

**Comment by olefredrik** [comment]
No worries

**Comment by GarySwift** [comment]
I wanted to pull the other way. This is still new to me. Sorry again:-)

**Comment by olefredrik** [comment]
You can pull in the latest master by typing ```git pull origin master``` , as long as your remote origin is pointing to git@github.com:olefredrik/FoundationPress.git

**Pull request closed without merging**
