### PR TITLE
Foundation update

### PR DESCRIPTION
**Pull request by olefredrik**
Okay, so here it is. FoundationPress is now based on [Foundation 6.4.1](https://github.com/zurb/foundation-sites/releases/tag/v6.4.1). That means we've got a new (and better way) for writing and using layouts with XY-Grid. The old float based grid is disabled by default, but is still a part of the project if you need to support legacy browsers. JavaScript is now bundled and loaded with webpack. And a lot of issues are addressed. I think that it has generally become a better and more robust theme.

We have removed some dependencies like bower. As a consequence of the changes that was introduced in Foundation 6.4.1, the Gulpfile is also changed. This is more or less copied from the [Zurb Template](https://github.com/zurb/foundation-zurb-template), with only a few adjustments to make it work in a WordPress context.

Last but now least, the README file is obviously updated with the new instructions.

Enjoy!  🚀

### CODE REVIEW

**Comment by Verscienta** [comment]
Awesome! Great work.

**Comment by kekkorider** [comment]
Thanks a lot @olefredrik

**Comment by dantahoua** [comment]
Awesome! Merci!

**Comment by kavasey** [comment]
Thank you @olefredrik for the great work done.

**Comment by linuxbastard** [comment]
So far so good, did an update, did another npm install and everything is still working :+1:

**Pull request merged**
