### PR TITLE
Move custom templates to subfolder

### PR DESCRIPTION
**Pull request by olefredrik**
Caution: Renaming a page template — and that includes moving all of top-level page templates into a directory — will unassign that page template for all pages currently using it. 

More info: http://nacin.com/2012/03/29/page-templates-in-subdirectories-new-in-wordpress-3-4/

### CODE REVIEW

**Comment by AdamChlan** [comment]
I like to create my templates using page-slug.php, which allows WP to auto select the right template based on the page slug, and allows me to leave the template as default in the page option dropdown. This functionality does not work after using the /template folder to store template files. Anyone aware of a workaround for this?

**Comment by Aetles** [comment]
The folder should be named `page-templates` to be [recognized by WordPress](https://developer.wordpress.org/themes/template-files-section/page-template-files/page-templates/#file-organization-of-page-templates).

**Comment by AdamChlan** [comment]
Gotcha, thanks. I also see this note:

Alert: A specialized page template file (those created for only one time use) cannot be in a sub-folder, nor, if using a Child Theme, in the Parent Theme’s folder.

Looks like I'll need to pull out my one time templates into the main theme folder.

**Comment by Aetles** [comment]
Ah, yeah that's a condition too in your case (I wonder why, seems like something that should be fixed in WP core).

**Pull request merged**
