### PR TITLE
Gruntfile with task time tracking and livereload

### PR DESCRIPTION
**Pull request by radel**
I found myself adding these two features every time I clone the upstream repository for my themes, so I figured a pull request would be appreciated by someone.

I work in a local environment with vagrant and livereload is very handy and fast, but somebody may not like livereload on php file changes. Do as you like and add what you want the way you want ;)

Livereload needs a [chrome/firefox extension](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei)  to work.

### CODE REVIEW

**Comment by olefredrik** [comment]
Super nice! Thanks :+1:

**Comment by radel** [comment]
Great! Thank you!

**Comment by Aetles** [comment]
Is there a reason why time-grunt is placed under ´dependencies´ instead of ´devDependencies´?

**Comment by olefredrik** [comment]
No, time-grunt should be placed under ```devDependencies```. I'll fix it.

**Pull request merged**
