### PR TITLE
removed global dependency of bower and grunt - #274

### PR DESCRIPTION
**Pull request by stefanjudis**
I removed the need for global installation of Grunt and Bower.

Basically it's working the same as before. :)

### CODE REVIEW

**Comment by olefredrik** [comment]
This is quite clever. A nice simplification of the installation workflow. Well done! Thank you for your contribution :+1:

**Comment by Aetles** [comment]
It could be worth pointing out for those who been using FoundationPress for a long time that this change means that the commands for compiling SASS has change. (Or will the old `grunt watch` continue to work?)

**Comment by stefanjudis** [comment]
@Aetles 

If you have bower and grunt installed globally (which you probably have when you used FoundationPress before) everything is working fine and the same as before.

For starters grunt task have to be used through npm (if grunt is not globally available).

E.g.

```
$ npm run grunt -- watch
$ npm run grunt -- sass
$ npm run grunt -- some_other_fancy_task
```

Maybe we wanna at some notes or point to an article explaining how this `--` with npm scripts work.

Wrote also about it. :bowtie: 

http://4waisenkinder.de/blog/2014/10/18/npm-2-dot-0-and-the-much-better-star-npm-run-star-command/

**Comment by olefredrik** [comment]
Yup. Everything will work the same as before if you have bower and grunt installed globally. But I should probably do another screencast on the FoundationPress installation. This will no longer be relevant https://www.youtube.com/watch?v=s4m5wwM4BWM :)

**Comment by stefanjudis** [comment]
@olefredrik 

Oh nice! Great that you're doing screencasts about this! :+1: 

If I can support somehow let me know. :bowtie:

**Comment by olefredrik** [comment]
:+1:  :+1:

**Comment by Aetles** [comment]
Yeah, I know about the new commands like `npm run grunt -- sass `, I've read the diff of README.md, I just wanted to bring up that this could be worth pointing out a little extra since it could confuse old time users (and breaks all current tutorials, screencasts on FoundationPress etc.) 

Nice to know though that the old commands still works (as long as grunt is still installed globally), that will ease the transition while relearning the new way :)

**Comment by stefanjudis** [comment]
@Aetles 

Yeah - agree on that. We might wanna guide this a bit more. 

But not sure about the detail of that tbh.

**Pull request merged**
