### PR TITLE
Added Turkish translations.

### PR DESCRIPTION
**Pull request by hocu**
Added Turkish translations.

### CODE REVIEW

**Comment by hocu** [comment]
OK I'm working on this now.

**Comment by olefredrik** [comment]
Hi @hocu : It seems like the travis-ci error is caused by a change in the wordpress coding standards ruleset, not by the changes in your pull request. I can have a look at it, and restart the build as soon as this is fixed.

**Comment by hocu** [comment]
OK thanks, I was investigating this and you saved me a lot of time.

**Comment by olefredrik** [comment]
@hocu : Hi. I have fixed the travis-ci build issues. Can you please resolve the merge conflicts, so I can merge your pull request? (Basically, just checkout the .travis.yml and readme.md files)

**Comment by hocu** [comment]
Sure i will do it on monday.

**Comment by olefredrik** [comment]
@hocu : Did you remove the language files? I'm only seeing 1 files changed in this PR, and that is .travis.yml ..?

**Comment by hocu** [comment]
@olefredrik I had some problems with the workstation, I might have done so, I will update the files for the new version. Let's close this, shall we?

**Pull request closed without merging**
