### PR TITLE
Optimize CSS & Sync with Vanilla Foundation

### PR DESCRIPTION
**Pull request by EricRihlmann**
Take a look at the extended commit messages for further details.

### CODE REVIEW

**Comment by EricRihlmann** [comment]
Travis is failing because the WP Coding Standards aren't loading. Try rerunning Travis to see if the issue has been resolved.

`The command "scripts/phpcs --config-set installed_paths ../wordpress-coding-standards" failed and exited with 127 during`

**Comment by olefredrik** [comment]
@EricRihlmann : Unfortunately there has been quite a few cases where WP Coding Standards have not worked as expected. Not sure what `failed and exited with 127 during .` exactly means. Would be great with a better explanation of what's really going on. Will try and search for an answer. I basically like the idea of being compliant to established coding standards. But it would be awesome if the travis build system could just ... work.

**Comment by EricRihlmann** [comment]
@olefredrik Ultimately the problem was that the WordPress Coding Standards are not compatible yet with version `3.0` of PHP Code Sniffer (complete rewrite). For now I locked PHPCS to version `2.9` in the Travis config. Also, getting all of this working again revealed a bunch of WPCS violations in FoundationPress, so I went ahead and corrected them and added the commit to this pull request. 

FYI, for the other open pull requests, you should be able to rerun the builds (I can't see the button because I don't have access to the repo). You can also just close then reopen a PR to force a the build rerun.

**Comment by olefredrik** [comment]
Good stuff, @EricRihlmann ! Thanks for all the time and effort you have put into this! 👍

**Comment by Aetles** [comment]
Thank you @EricRihlmann for fixing Travis and cleaning up inconsistencies in the code. 

Just a thought: now that Travis is running and FoundationPress code is more standard compliant, wouldn't it be a good time to revisit the discussion of the [exclusions from WPCS](https://github.com/olefredrik/FoundationPress/commit/290a66a02dd6f73e204038a389d63b7160e95ef3)?

**Pull request merged**
