### PR TITLE
Update enqueue-scripts.php

### PR DESCRIPTION
**Pull request by wishe**
Added filemtime to assets for cache bust

### CODE REVIEW

**Comment by olefredrik** [comment]
After running ``npm run build`` I now get

``<link rel='stylesheet' id='main-stylesheet-css'  href='http://foundationpress:8888/wp-content/themes/FoundationPress/dist/assets/css/app.css?ver=4.7' type='text/css' media='all' />``

Don't know where ``?ver=4.7`` comes from? It does not change after running another ``npm run build``. 

For this to work as a cache buster, I would expect that a new random hash (or similar) was generated on each ``npm run build`` and automatically appended at the end of the url for static assets in the ``enqueue_scripts.php`` file.

**Comment by wishe** [comment]
Sorry, i used the wrong function to get the file path, should work now.

**Comment by olefredrik** [comment]
@wishe : With your latest commit, the ``app.js`` file loaded in the footer does now get a new timestamp on every ``npm run build``. However, the timestamp for ``app.css`` file seems to stay the same.

There is an [article on CSS-Tricks](https://css-tricks.com/hashes-in-wordpress-assets-with-enqueue/) the issues with cache breaking in WordPress. The author of the article recommends to generate random hashes and add it dynamically through Gulp, instead of using the ``filemtime`` function. What are your thoughts around this?

**Comment by wishe** [comment]
@olefredrik Not sure why the timestamp on the css file stays the same, I have only used this method with the old FoundationPress build and found it works well there. This Pull Request may be a bit premature, will need to test this method more then.

The hashing method outlined in the article you posted is definitely the superior method but it is a little bit more work to implement.

**Comment by olefredrik** [comment]
I can't say why it didn't work with the css file, but it didn't. Tested in Chrome and Opera, and the timestamp did not change after changing the content of a .scss file followed by a ``npm run build``.

**Comment by olefredrik** [comment]
As I could not get this to work, and we should rather aim for a random hash generated by a gulp build, I will close this pull request. Thanks for your efforts anyway 👍

**Pull request closed without merging**
