### PR TITLE
Bugfix for figure tag

### PR DESCRIPTION
**Pull request by derweili**
Wordpress adds a with attribute to every figure tag, breaking the whole
layout if the image width is wider than its conainer.
You can see this here: https://foundationpress.olefredrik.com/posts/post-with-an-image-and-caption

I added a filter to remove the width attribute

### CODE REVIEW

**Comment by derweili** [comment]
Before:
bildschirmfoto 2016-06-21 um 20 16 17

After:
bildschirmfoto 2016-06-21 um 20 16 00


Foundation adds a margin to the figure tag. That's why the large image isn't displayed in full-width.

**Comment by olefredrik** [comment]
Hi @derweili . Sorry for the late reply. I've been busy with other things for a while now. I'll review and test your PR as soon as I get the chance. Thanks for your contribution! :) Cheers!

**Comment by derweili** [comment]
@olefredrik no problem. I just moved the add_filter method inside the foundationpress_start_cleanup function to match the structure of the cleanup.php file.

Not Travis CI throws errors inside files files i haven't changed.

**Comment by olefredrik** [comment]
@derweili : I have review and tested your pull request, and it works very well. There has been some changes to the wordpress coding standards package lately. I have merged [a fix](https://github.com/olefredrik/FoundationPress/pull/855/files) for the sniffing violations to the master branch. 

I see there is still [one error in your pull request](https://travis-ci.org/olefredrik/FoundationPress/jobs/140900575#L306) , regarding whitespace at end of line. Can you fix this, so I can merge your pull request? Thanks! :)

**Comment by derweili** [comment]
I removed the whitespace. Now Travis CI shouldn't throw any errors.

**Pull request merged**
