### PR TITLE
Update Sass settings variables in Foundation 6.0.6

### PR DESCRIPTION
**Pull request by colin-marshall**
Source: https://github.com/zurb/foundation-sites/releases/tag/v6.0.6

**Changed:** $button-margin to 0 0 $global-margin 0 from 0 $global-margin $global-margin 0.
**Changed:** $topbar-background to $light-gray from #eee.
**Changed:** $topbar-link-color to $primary-color from #fff.

### CODE REVIEW

**Comment by Aetles** [comment]
Is it wise to change parts of FoundationPress to new versions of Foundation before support for that version is added? I mean, like adding Foundation 6.0.6 changes to FoundationPress that currently supports Foundation 6.0.5. Wouldn't it be better to wait and make all those changes at once?

**Comment by colin-marshall** [comment]
@Aetles that is a good question. Are you aware that 6.0.6 is already what gets installed on a fresh install of FoundationPress since `bower.json` has `"foundation-sites": "~6.0.5"`? As is, up to version 6.0.9 will be installed without any updates to FoundationPress, so version 6.0.6 is already used in new installs of FoundationPress from the moment it became available on bower.

Also, I went over the release notes (linked in OP) and only found that the Sass variables needed to be changed. I did forget to bump the version # in `bower.json` to 6.0.6, but I just fixed that. If you see anything I missed in the release notes please let me know.

If we were to pretend that there were more than just the Sass variables that needed updating in 6.0.6 then @olefredrik is always welcome to hold off on my PR until the remaining changes are made in other PR's.

**Comment by Aetles** [comment]
> Are you aware that 6.0.6 is already what gets installed on a fresh install of FoundationPress since bower.json has "foundation-sites": "~6.0.5"?

No, I wasn't aware of that. Then the PR makes sense. 

My main concern was if further down the line there would be Sass changes that would throw an error with previous version of Foundation (not in this PR, but theoretically). I know such changes shouldn't occur with x.x.1 updates, but as they said [in the 6.0.4 release](https://github.com/zurb/foundation-sites/releases/tag/v6.0.4) that could happen:

> Breaking Changes
Yes, there are a few. We're going to abuse semver a little bit at the beginning here while we massage the Sass API.

**Comment by olefredrik** [comment]
Fixed in https://github.com/olefredrik/FoundationPress/pull/656

**Pull request closed without merging**
