### PR TITLE
Improved Method to Check For Direct Access to a File

### LINKED ISSUE #308: Fatal error:
Have just started developing a theme with Foundationpress. Nothing has been done other than set up a static 'front-page.php' and change text domain. The following error is now being thrown on front page and post pages. Seems to have been caused by the front page somehow.

Fatal error: Can't use function return value in write context in C:\Program Files\Ampps\www\retro-resources-v4\wp-content\themes\retroresouces\comments.php on line 39

If anyone can shed some light on this issue it would be much appreciated.

Anthony

### PR DESCRIPTION
**Pull request by josh-rathke**
Fixes #308.

### CODE REVIEW

**Comment by olefredrik** [comment]
Sweet! But unfortunately the Travis CI build failed with the following error

```
FILE: ...tmp/wordpress/src/wp-content/themes/FoundationPress/comments.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 39 | ERROR | [x] Whitespace found at end of line
    |       |     (Squiz.WhiteSpace.SuperfluousWhitespace.EndLine)
```

any chance you could fix the error and push a new commit?

**Comment by josh-rathke** [comment]
Got it, should be fixed now.

**Comment by olefredrik** [comment]
:+1:

**Comment by LukePettway** [comment]
Awesome! Learned something new too!

**Pull request merged**
