### PR TITLE
Removed duplicate what-input.js path

### PR DESCRIPTION
**Pull request by EricRihlmann**
The `gulpfile.js` had a duplicate reference to `assets/components/what-input/what-input.js`. I removed the first reference and kept the second one with the comment above it.

### CODE REVIEW

**Comment by colin-marshall** [comment]
Thanks @EricRihlmann. This was my fault. If you don't mind, would you actually remove the 2nd reference to what-input instead of the first please? I'm trying to keep it the same as: https://github.com/zurb/foundation-zurb-template.

Also, please fix the build errors so it can be merged. Thanks!

**Comment by EricRihlmann** [comment]
@colin-marshall no worries, I just pushed a commit with your suggestion. 

About the build errors, they appear to be completely unrelated to my changes. The errors are with improper case for two PHP variables. How did you get your builds to pass?

```
FILE: ...dpress/src/wp-content/themes/FoundationPress/library/cleanup.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 247 | ERROR | Variable "Foundationpress_img_rebuilder" is not in valid
     |       | snake_case format
     |       | (WordPress.NamingConventions.ValidVariableName.NotSnakeCase)
----------------------------------------------------------------------
FILE: ...hemes/FoundationPress/library/protocol-relative-theme-assets.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 90 | ERROR | Variable "Foundationpress_protocol_relative_theme_assets"
    |       | is not in valid snake_case format
    |       | (WordPress.NamingConventions.ValidVariableName.NotSnakeCase)
----------------------------------------------------------------------
```

**Comment by colin-marshall** [comment]
@EricRihlmann you can copy the changes from my PR to fix those build errors:
https://github.com/olefredrik/FoundationPress/pull/644/files

**Comment by EricRihlmann** [comment]
Shouldn't I just ignore the build errors since my pull request is unrelated to them? Plus you've already issued a PR with a fix.

**Comment by colin-marshall** [comment]
Can a PR still be merged if it has a build failure? If so, then yes you are correct and you can leave it as is. I'm a noob when it comes to the build stuff.

**Comment by olefredrik** [comment]
Fixed in https://github.com/olefredrik/FoundationPress/pull/656

**Pull request closed without merging**
