### PR TITLE
check if function exists

### PR DESCRIPTION
**Pull request by Stevie-Ray**
if you use foundationpress with a child theme, you get an error.

PHP Fatal error:  Cannot redeclare foundationpress_breadcrumb()

### CODE REVIEW

**Comment by olefredrik** [comment]
Hi. Can not merge as the test have failed. There seems to be 45 errors in navigation.php. Could you fix the errors and push a new commit? https://travis-ci.org/olefredrik/FoundationPress/jobs/72619330#L225

**Comment by KLVTZ** [comment]
@Stevie-Ray PSR-2 violations, easily fixed if you just follow the messages. This would be very useful to get this pulled in as it causes some issues if you where to copy it from parent to child. 

We noticed an alternative fix would be for you just to create a `library/navigation.php` file within your child theme and use that in addition to parent. Our use shows that wordpress will still use both and not overwrite on or the other. Since of course functions only exist in parent and not child.

**Comment by Stevie-Ray** [comment]
It seems to work ok now

**Comment by olefredrik** [comment]
:+1:

**Pull request merged**
