### PR TITLE
Added missing check for $separatorclass for single pages

### PR DESCRIPTION
**Pull request by Larzans**
For the single page view the separator class would be shown even if the $separatorclass was false

### CODE REVIEW

**Comment by Larzans** [comment]
btw, is there a way to stop the travis checks if there is a newer commit by the same author? Now the second commit hasn't even started and the third one will be only checked once the second one is done, but i know it will fail.
It should be skipped...
Seems like a waste of resources...

**Comment by Larzans** [comment]
Hm, it didn't fail after all, strange.
Anyhow it should just skip to the current commit by the user and forget all the in-between checks me thinx.

**Comment by olefredrik** [comment]
I know what you mean. I'll check what I can do in Travis settings.

**Comment by Larzans** [comment]
I mean it all works fine, just an idea for optimization, energy saving and such ;)
Maybe thats how travis works and no way around it, i have no idea

**Pull request merged**
