### PR TITLE
Gulp

### PR DESCRIPTION
**Pull request by colin-marshall**
Here is what I have so far. It's not ready to be merged as I haven't removed Grunt from this branch yet. That's my next task, but here it is so you can see what I have so far @olefredrik.

To make the `gulpfile.js` I modeled the imports, paths, and tasks off of your `Gruntfile.js`. The actual logic inside of the tasks is modeled after the gulpfile from the [Foundation Zurb Template](https://github.com/zurb/foundation-zurb-template).

I have implemented Browsersync but not LiveReload. It doesn't seem as feasible to have both in Gulp as we did in Grunt. I could be wrong though.

Let me know what you think when you get a chance please! Thanks!

### CODE REVIEW

**Comment by olefredrik** [comment]
@colin-marshall : This is awesome! Great job! I will review and test after work today.

**Comment by colin-marshall** [comment]
Thanks!!! Looking forward to your feedback.

**Comment by jimlongo56** [comment]
@colin-marshall How do I get the **foundation.css** to minify?  I tried to set 
`var isProduction = true;`   and also `var isProduction = arg.production;` but neither results in a compressed output.

However the **foundation.js is minified** in the default setting `var isProduction = !!(arg.production);`

**Comment by jimlongo56** [comment]
One last question before I leave . . . can you explain the direction given during build

    [BS] Copy the following snippet into your website, just before the closing </body> tag
        <script type='text/javascript' id="__bs_script__">//<![CDATA[
        document.write("<script async src='http://HOST:3002/browser-sync/browser-sync-    client.2.10.0.js'><\/script>".replace("HOST", location.hostname));
    //]]></script>

    [BS] Access URLs:
     -------------------------------------
              UI: http://localhost:3003
     -------------------------------------
     UI External: http://192.168.50.1:3003

Thanks again for everything!

**Comment by colin-marshall** [comment]
@jimlongo56 to get the CSS to minify, you do `npm run production` instead of `npm run watch`. That just runs gulp with the --production flag(`gulp --production`). You can also run `gulp build --production` if you don't want the watch task to also run. Going to fix that javascript issue now, I just forgot to add in a conditional to minify.

The part that says to copy the snippet will go away if you add the url to the site you are working on with local development server. You add it towards the top of `gulpfile.js` Then when Gulp runs Browsersync will open a new tab with your site that automatically reloads.

**Comment by jimlongo56** [comment]
Cool, thanks.

**Pull request merged**
