### PR TITLE
Introducing $content width

### PR DESCRIPTION
**Pull request by glueckpress**
I’ve chosen this theme for a project and will be working on it either way, and I can do more than [this](https://github.com/olefredrik/FoundationPress/pull/317). :) So I’ve run a simple [Theme Check](https://wordpress.org/plugins/theme-check/), and it complains. (Which isn’t neither intrinsically good, nor bad, of course.)

Unrelated to the question whether or not the theme author’s might intend to make his work available via the wordpress.org theme repo one day, I wanted to ask if contributions regarding basic Theme Check compliance would be received as valuable? 

Here’s one for `$content_width` for example. I don’t expect it to be merged directly, but would love your feedback on it.

### CODE REVIEW

**Comment by olefredrik** [comment]
Hi, 

Thanks for stopping by :) I'm glad that you've chosen this theme for your project. 

I was curious about the Theme Check, so I did a check on the demo site on my localhost. And you're totally right. It complains. A lot actually. But much of what the complaints are concerned, does not make sense at all in a modern web development perspective. At least if you ask me. 

```
REQUIRED:.wp-caption-text css class is needed in your theme css.
REQUIRED:.sticky css class is needed in your theme css.
REQUIRED:.gallery-caption css class is needed in your theme css.
REQUIRED:.bypostauthor css class is needed in your theme css.
WARNING: The theme uses the add_shortcode() function. Custom post-content shortcodes are plugin-territory functionality.
WARNING: .bowerrc .ds_store .git .gitignore .travis.yml .bower.json .npmignore .editorconfig .bin .gitmodules .jshintrc .gitattributes .hidden .tern-port .gitignore.orig .gitignore.rej .dntrc .npmrc .eslintrc .dir-locals.el .jshintignore .documentup.json .gitkeep Hidden Files or Folders found.
```

Why should a CMS tell me what CSS classes I need? I don't get it. For various reasons, I have no plans to publish FoundationPress under the official WordPress theme repository. This will never be a one-click-install via wp-admin theme, since it depends on Grunt, Node and Bower to function optimally.

When all this is said, I am very interested to see if your ```$content_width``` fix can add extra value to the theme. A couple of weeks ago the brilliant @josh-rathke introduced [a set of tests](https://github.com/olefredrik/FoundationPress/commits?author=josh-rathke) ensuring WordPress Coding Standards compliance. Unfortunately your commit https://github.com/glueckpress/FoundationPress/commit/f85a45cde7286b543665b08bc75a3cb639803d8d is [failing the build](https://travis-ci.org/olefredrik/FoundationPress/jobs/60861102). Would you mind having a look at it? 

Cheers,
Ole Fredrik

**Comment by Aetles** [comment]
Theme Check seems reasonable *if* the theme is meant as traditional wordpress.org theme, with all that comes with that. Since FoundationPress is none of that it does make the same sense to try to support those complaints.

(That being said, I find myself adding basic gallery CSS for the native WP galleries (from one of the default themes, like Twenty Thirteen) to almost all my FoundationPress-sites so I think that could be considered useful. I would assume most users of FoundationPress are looking for some basic CSS design out of the box, otherwise they would not use a framework like Foundation to begin with and rather go with themes like Underscores.)

**Comment by glueckpress** [comment]
> Unfortunately your commit glueckpress@f85a45c is failing the build. Would you mind having a look at it?
Will asap!

**Comment by glueckpress** [comment]
> For various reasons, I have no plans to publish FoundationPress under the official WordPress theme repository.

Totally can see why, so no priority from my side for those CSS classes. `$content_width` however actually [does something](https://wycks.wordpress.com/2013/02/14/why-the-content_width-wordpress-global-kinda-sucks/), even if it sucks a bit. :)

**Pull request closed without merging**
