### PR TITLE
Take 2: Optimize responsive images for 3/4 and full width templates

### PR DESCRIPTION
**Pull request by EricRihlmann**
Currently the function `foundationpress_adjust_image_sizes_attr` is not factoring in several display variables during the creation of `` tag `sizes` attribute value. I've updated it to take in account the actual size of the image, the gutters, and the current template.

### CODE REVIEW

**Comment by EricRihlmann** [comment]
@olefredrik looks Travis kicked off this time.

**Comment by olefredrik** [comment]
Thanks, @EricRihlmann !

**Comment by Aetles** [comment]
Is it a good idea to hard code these detailed values? It seems very specific (1200, 770 etc), will people understand the need to change these values if they don't use the same page width or if they have a full width page that is _not_ named `page-full-width.php`?

**Comment by EricRihlmann** [comment]
@Aetles I based this pull request off of how the default [Twenty Sixteen](https://github.com/WordPress/twentysixteen/blob/master/functions.php#L371) theme sets these values. You would also have to hunt down and update the values if you were to modify the CSS or add a new custom template in that theme as well. I don't believe there is currently anywhere in the FoundationPress PHP that stores the corresponding sass breakpoint and gutter values. Have any suggestions?

**Comment by Aetles** [comment]
No, really, I haven't really used responsive images in WordPress yet. I was just looking at the code, and thinking about it and if it would introduce issues, being som specific. 

On one hand, if it's from Twenty Sixteen then we can assume it is reasonable and tested code. On the other hand, the templates and layout in Twenty Sixteen is probably not as flexible as the Foundation grid is. I'll guess we'll have to wait and see how well it works when people start using it.

**Pull request merged**
