### PR TITLE
Made it easier to understand

### PR DESCRIPTION
**Pull request by alexbohariuc**
I made a small change (closed the php tag and got the images with echo) - it is easier to understand the code this way.

### CODE REVIEW

**Comment by olefredrik** [comment]
Thanks! Can you fix the Travis-CI build error and add a new commit? https://travis-ci.org/olefredrik/FoundationPress/jobs/95248578

**Comment by Aetles** [comment]
It's also a div with the title that was not there before, right?

**Comment by olefredrik** [comment]
Well spotted. Why would we need that extra div @alexbohariuc ?

**Comment by alexbohariuc** [comment]
I did some design changes for a project. I will remove it and then add a new commit.

**Comment by Aetles** [comment]
Not so hard to spot if you read the diff, was only five new lines… 😉

**Pull request merged**
